dist: trusty
sudo: required
language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - docker-ce
      env:
          - DOCKER-VERSION: latest
      before_install:
        - sudo docker --version
        - sudo docker build -t karabo-bridge-server -f tests/server.Dockerfile tests
        - sudo docker build -t karabo-bridge-client .
        - sudo docker network create mynet
      script:
        - sudo docker run --rm --name server --net mynet karabo-bridge-server /bin/bash -c "karabo-bridge-server-sim 1234 -n 2"&
        - sudo docker run --rm -it --net mynet karabo-bridge-client /bin/bash -c "pushd karabo-bridge-cpp && ./autogen.sh integration_test /root/share server:1234"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-5
            - python3.6
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && PYTHON=3.6"
      before_install:
        - eval ${MATRIX_EVAL}
        - python${PYTHON} -V
        - cmake --version
        # pip
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - sudo python${PYTHON} get-pip.py
      install:
        - pushd ..
        # simulator
        - git clone https://github.com/European-XFEL/karabo-bridge-py
        - pushd karabo-bridge-py
        - sudo python${PYTHON} -m pip install -e .
        - popd
        # karabo-bridge-cpp
        - popd
        - ./autogen.sh test
      
      script:
        - karabo-bridge-server-sim 1234 -n 2&
        - ./autogen.sh integration_test
