dist: trusty
sudo: required
language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - docker-ce
      script:
        - docker-compose up --build --exit-code-from client
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      before_install:
        - MINCONDA_OS=$MINCONDA_LINUX
        - wget "http://repo.continuum.io/miniconda/Miniconda3-${MINCONDA_VERSION}-${MINCONDA_OS}.sh" -O miniconda.sh
        - bash miniconda.sh -b -p ${HOME}/miniconda
        - export PATH="${HOME}/miniconda/bin:${PATH}"
        - conda config --set always_yes yes
        - conda update -q conda
      install:
        # install dependencies
        - conda install -c anaconda cmake
        - conda install -c omgarcia gcc-6
        - conda install -c conda-forge cppzmq msgpack-c
        # install Python bridge for integration test
        - pip install karabo-bridge
      script:
        - export PATH="${HOME}/miniconda/bin:${PATH}"
        - export LD_LIBRARY_PATH="${HOME}/miniconda/lib"
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON -DBUILD_INTEGRATION_TEST=ON -DBUILD_EXAMPLES=ON ../
        - make && make test
        - karabo-bridge-server-sim -d AGIPD -n 2 1234&
        - integration_test/pysim_client localhost:1234

env:
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"