dist: trusty
sudo: required
language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - docker-ce
      env:
          - DOCKER-VERSION: latest
      before_install:
        - sudo docker --version
        - sudo docker build -t karabo-bridge-server -f tests/server.Dockerfile tests
        - sudo docker build -t karabo-bridge-client .
        - sudo docker network create mynet
      script:
        - sudo docker run --rm --name server --net mynet karabo-bridge-server&
        - sudo docker run --rm -it --net mynet karabo-bridge-client /karabo-bridge-cpp/build/run1 server:1234
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_install:
        - eval ${MATRIX_EVAL}

      install:
        # ZeroMQ
        - wget https://github.com/zeromq/libzmq/releases/download/v4.2.5/zeromq-4.2.5.tar.gz
        - tar -xvzf zeromq-4.2.5.tar.gz
        - cd zeromq-4.2.5
        - ./configure -prefix=${HOME}/share/zeromq
        - make -j${nproc}
        - make install
        - cd ..
        # cppzmq
        - wget https://github.com/zeromq/cppzmq/archive/v4.2.2.tar.gz
        - tar -xvzf v4.2.2.tar.gz
        - mkdir -p ${HOME}/share/cppzmq/include
        - cp cppzmq-4.2.2/*.hpp ${HOME}/share/cppzmq/include/
        # msgpack
        - wget https://github.com/msgpack/msgpack-c/archive/cpp-2.1.5.tar.gz
        - tar -xvzf cpp-2.1.5.tar.gz
        - mkdir -p ${HOME}/share/msgpack
        - cp -r msgpack-c-cpp-2.1.5/include ${HOME}/share/msgpack/
        # karabo-bridge-cpp
        - mkdir build && cd build
        - cmake ..
        - make -j${nproc}
      
      script:
        - make test
