version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: karabo-bridge-client
    links:
      - server
    command: bash -c "export PATH=/root/miniconda/bin:${PATH} &&
                      export LD_LIBRARY_PATH=/root/miniconda/lib &&
                      karabo-bridge-cpp/build/integration_test/pysim_client server:1234"
  server:
    build:
      context: ./tests
      dockerfile: server.Dockerfile
    image: karabo-bridge-server
    expose:
      - "1234"
    command: bash -c "pushd karabo-bridge-py &&
                      pip install --upgrade . &&
                      karabo-bridge-server-sim -d AGIPD -n 2 1234"
