version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: karabo-bridge-client
    links:
      - server
    command: bash -c "make -C /karabo-bridge-cpp/build test && /karabo-bridge-cpp/build/run1 server:1234"
  server:
    build:
      context: ./tests
      dockerfile: server.Dockerfile
    image: karabo-bridge-server
    expose:
      - "1234"
