version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: karabo-bridge-client
    links:
      - server
    command: bash -c "pushd karabo-bridge-cpp && ./autogen.sh clean && ./autogen.sh integration_test /root/share server:1234"
  server:
    build:
      context: ./tests
      dockerfile: server.Dockerfile
    image: karabo-bridge-server
    expose:
      - "1234"
    command: bash -c "pushd karabo-bridge-py && pip install --upgrade . && karabo-bridge-server-sim 1234 -n 2"
